<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:tns="http://xml.transformacion.com/transformacion" 
                  targetNamespace="http://xml.transformacion.com/transformacion" 
                  xmlns:getTransformacionIn ="http://xml.transformacion.com/getTransformacionRequest"
                  xmlns:getTransformacionOut ="http://xml.transformacion.com/getTransformacionResponse"
>
    <wsdl:types>
        
        <xsd:schema name="http://xml.transformacion.com/transformacion">
            <xsd:import namespace="http://xml.transformacion.com/getTransformacionRequest" schemaLocation="http://localhost/webServiceTransformacion/contracts/xsd/getTransformacionRequest.xsd" />
            <xsd:import namespace="http://xml.transformacion.com/getTransformacionResponse" schemaLocation="http://localhost/webServiceTransformacion/contracts/xsd/getTransformacionResponse.xsd" />
        </xsd:schema>
        
    </wsdl:types>
        
    
    <wsdl:message name="getTransformacionRequest">
        <wsdl:part name="in" element="getTransformacionIn:getTransformacionRequest" />
    </wsdl:message>
    <wsdl:message name="getTransformacionResponse">
        <wsdl:part name="out" element="getTransformacionOut:getTransformacionResponse" />
    </wsdl:message>
    
    <wsdl:portType name="getTransformacion">
        <wsdl:operation name="getTransformacion">
            <wsdl:input message="tns:getTransformacionRequest" />
            <wsdl:output message="tns:getTransformacionResponse" />
        </wsdl:operation>
    </wsdl:portType>    
    
    <wsdl:binding name="transformacionSoap" type="tns:getTransformacion">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
        
        <wsdl:operation name="getTransformacion">
            <soap:operation soapAction="http://xml.transformacion.com/getTransformacion"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    
    </wsdl:binding>
    
    <wsdl:service name="transformacion">
        <wsdl:port binding="tns:transformacionSoap" name="transformacionSoap">
            <soap:address location="http://localhost/webServiceTransformacion/server.php" />
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>

